server:
  port: 8081

## mysql
spring:
  datasource:
    url:  jdbc:mysql://106.52.167.184:3306/community?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username: root
    password: pwkingzxli1991
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    
# 输出sql
logging:
  level:
    com.community.mapper: debug
    
# mybatisplus 逻辑删除
mybatis-plus:
  global-config:
    db-config:     
      logic-delete-value: 1
      logic-not-delete-value: 0
      
# 微信支付参数
appid: wx23db2e5b441b70fc
mch_id: 1601076593
notify_url: http://changshengwuye.cn:9999/zcw/
type: JSAPI
key: changshengwuye202008121458000000
wxpay_url: https://api.mch.weixin.qq.com/pay/unifiedorder

#pagehelper:
#  # dialect: ①
#  # 分页插件会自动检测当前的数据库链接，自动选择合适的分页方式（可以不设置）
#  helper-dialect: mysql 
#  # 上面数据库设置后，下面的设置为true不会改变上面的结果（默认为true）
#  auto-dialect: true 
#  page-size-zero: false # ②
#  reasonable: true # ③
#  # 默认值为 false，该参数对使用 RowBounds 作为分页参数时有效。（一般用不着）
#  offset-as-page-num: false 
#  # 默认值为 false，RowBounds是否进行count查询（一般用不着）
#  row-bounds-with-count: false 
#  #params: ④
#  #support-methods-arguments: 和params配合使用，具体可以看下面的讲解
#  # 默认值为 false。设置为 true 时，允许在运行时根据多数据源自动识别对应方言的分页
#  auto-runtime-dialect: false # ⑤
#  # 与auto-runtime-dialect配合使用
#  close-conn: true 
#  # 用于控制默认不带 count 查询的方法中，是否执行 count 查询，这里设置为true后，total会为-1
#  default-count: false 
#  supportMethodsArguments: true

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql




