server:
  port: 8081

## mysql
spring:
  datasource:
    url:  jdbc:mysql://106.52.167.184:3306/community?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username: root
    password: pwkingzxli1991
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    
# 输出sql
logging:
  level:
    com.community.mapper: debug
    
# mybatisplus 逻辑删除
mybatis-plus:
  global-config:
    db-config:     
      logic-delete-value: 1
      logic-not-delete-value: 0
      
# 微信支付参数
appid: wx23db2e5b441b70fc
mch_id: 1601076593
notify_url: http://changshengwuye.cn/zcw/index.html
type: JSAPI
key: changshengwuye202008121458000000
wxpay_url: https://api.mch.weixin.qq.com/pay/unifiedorder

#wechat:
#  appId: wx23db2e5b441b70fc
#  appSecret: 8fa2a01aca176430c3e1155f68346aba

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

wx:
  redirect: 
    url: "http://changshengwuye.cn/index.html"
  response:
    url: "http://changshengwuye.cn/index.html"

